Error: In HTML, whitespace text nodes cannot be a child of <thead>. Make sure you don't have any extra whitespace between tags on each line of your source code. This will cause a hydration error.
  ...
    <ClientPageRoot Component={function HomePage} searchParams={{}} params={{}}>
      <HomePage params={Promise} searchParams={Promise}>
        <div className="flex h-scr...">
          <AppSidebar>
          <div className="flex-1 fle...">
            <AppHeader>
            <main className="flex-1 fle...">
              <div className="flex-1 fle...">
                <div>
                <DataDisplayTable data={[...]} columns={[...]} onSelectRecord={function handleOpenEditor} ...>
                  <div className="rounded-md...">
                    <div className="relative w...">
                      <_c>
                        <div className="relative w...">
                          <table ref={null} className="w-full cap...">
                            <_c14>
                            <_c2 className="sticky top...">
>                             <thead ref={null} className={"[&_tr]:border-b sticky top-0 bg-card z-10"}>
>                               {" "}
                                ...
                            ...
    ...

    at createUnhandledError (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at completeWork (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9585:87)
    at runWithFiberInDEV (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at completeUnitOfWork (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10233:23)
    at performUnitOfWork (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10170:28)
    at workLoopSync (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10060:40)
    at renderRootSync (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10043:13)
    at performWorkOnRoot (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:212)
    at performWorkOnRootViaSchedulerTask (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at thead (<anonymous>)
    at _c2 (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/src_66270a16._.js:446:452)
    at DataDisplayTable (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/src_66270a16._.js:611:227)
    at HomePage (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/src_66270a16._.js:2020:327)
    at ClientPageRoot (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)

Error: In HTML, whitespace text nodes cannot be a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <ClientPageRoot Component={function HomePage} searchParams={{}} params={{}}>
      <HomePage params={Promise} searchParams={Promise}>
        <div className="flex h-scr...">
          <AppSidebar>
          <div className="flex-1 fle...">
            <AppHeader>
            <main className="flex-1 fle...">
              <div className="flex-1 fle...">
                <div>
                <DataDisplayTable data={[...]} columns={[...]} onSelectRecord={function handleOpenEditor} ...>
                  <div className="rounded-md...">
                    <div className="relative w...">
                      <_c>
                        <div className="relative w...">
                          <table ref={null} className="w-full cap...">
                            <_c14>
                            <_c2 className="sticky top...">
                              <thead ref={null} className={"[&_tr]:b..."}>
                                <_c8>
>                                 <tr
>                                   ref={null}
>                                   className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-m..."
>                                 >
                                    <_c10>
                                    <_c10>
                                    <_c10>
                                    <_c10>
                                    <_c10>
>                                   {" "}
                            ...

    at createUnhandledError (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at completeWork (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9585:87)
    at runWithFiberInDEV (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at completeUnitOfWork (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10233:23)
    at performUnitOfWork (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10170:28)
    at workLoopSync (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10060:40)
    at renderRootSync (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10043:13)
    at performWorkOnRoot (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:212)
    at performWorkOnRootViaSchedulerTask (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at tr (<anonymous>)
    at _c8 (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/src_66270a16._.js:479:449)
    at DataDisplayTable (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/src_66270a16._.js:615:235)
    at HomePage (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/src_66270a16._.js:2020:327)
    at ClientPageRoot (https://6000-firebase-studio-1747248227726.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)